services:
  mysql:
    image: mysql:8.0
    container_name: mysql-alquila
    environment:
      MYSQL_ROOT_PASSWORD: arraylistos
      MYSQL_DATABASE: alquilatusvehiculos
      TZ: UTC
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  adminer: # UI web para ver la BD (en vez de phpMyAdmin)
    image: adminer
    container_name: adminer-alquila
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
